version: '3'

tasks:
  generate:
    cmds:
      - go run main.go test ServiceA ServiceB > test/service_locator_gen.go
    sources:
      - main.go
    generates:
      - test/service_locator_gen.go

  test:
    cmds:
      - go test -v ./test/
